name: nibbin_app
description: Bluone post sharing application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.5+13

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  google_fonts: ^1.1.0
#  flutter_bloc: ^6.0.1
#  bloc: ^6.0.2
#  equatable: ^1.2.3
  share: ^0.6.4+3
  rate_my_app: ^0.7.0
  webview_flutter: ^1.0.7
  google_sign_in: ^4.5.3
  rxdart: ^0.24.1
  intl: ^0.16.1
  sqflite: ^1.3.1+1
  path_provider: ^1.6.14
  firebase_messaging: ^7.0.0
  package_info: ^0.4.3
  url_launcher: ^5.5.2
  firebase_remote_config: ^0.4.0
  firebase_dynamic_links: ^0.6.0
  cloud_firestore: ^0.14.0+2
  flutter_screenutil: ^2.3.1
  speech_to_text: ^2.7.0
  visibility_detector: ^0.1.5
  amplitude_flutter: ^2.2.1
  firebase_auth: ^0.18.2
  apple_sign_in: ^0.1.0
#  flutter_cache_manager: ^2.0.0
  device_info: ^1.0.0
  flutter_html: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/